import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import { AuthProvider } from "@/components/Auth/AuthContext";
import "react-toastify/dist/ReactToastify.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-sans antialiased`}>
        <AuthProvider> {children}</AuthProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
