import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import DashboardLayout from "@/components/Dashboard/DashboardLayout";
import { Roboto } from "next/font/google";
import Footer from "@/components/Footer";
import AccountingLayout from "@/components/Accounting/AccountingLayout";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${roboto.className}   antialiased`}>
        <DashboardLayout>{children}</DashboardLayout>
        <Footer />
      </body>
    </html>
  );
}
